spring:
  datasource:
    url: jdbc:mysql://localhost:3306/vehicle_management?createDatabaseIfNotExist=True
    password: Quang2506
    username: root
  jpa:
    show-sql: true
    database: mysql
    properties:
      hibernate.show_sql: true
      hibernate.format_sql: true
    hibernate:
      ddl-auto: update